config/routes.rb
Blog::Application.routes.draw do
  resources :posts do
    resources :comments
  end
  resources :contacts, only: [:new, :create]

  devise_for :users

  get "home/index"
  get 'tags/:tag', to: 'posts#index', as: :tag

  root 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_no_table

  column :name, :string
  column :email, :string
  column :content, :string
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :content
  validates_format_of :email,
  :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_length_of :content, :maximum => 500
  def update_spreadsheet
    connection = GoogleDrive.login(ENV["GMAIL_USERNAME"], ENV["GMAIL_PASSWORD"])
    ss = connection.spreadsheet_by_title('LBlog')
    if ss.nil?
      ss = connection.create_spreadsheet('LBlog')
    end
    ws = ss.worksheets[0]
    last_row = 1 + ws.num_rows
    ws[last_row, 1] = Time.new
    ws[last_row, 2] = self.name
    ws[last_row, 3] = self.email
    ws[last_row, 4] = self.content
    ws.save
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_taggable # Alias for acts_as_taggable_on :tags
  belongs_to :user
  belongs_to :category
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  #before_create :create_login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login
=begin
  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end
=end

  validates :username, :uniqueness => { :case_sensitive => false }

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(conditions).first
    end
  end

  def create_login
    email = self.email.split(/@/)
    login_taken = User.where( :login => email[0]).first
    unless login_taken
      self.login = email[0]
    else
      self.login = self.email
    end
  end
=begin
  def self.find_for_database_authentication(conditions)
    self.where(:login => conditions[:email]).first || self.where(:email => conditions[:email]).first
  end
=end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :username, :email, :password, :password_confirmation, :remember_me) }
      devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name, :login, :username, :email, :password, :remember_me) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :username, :email, :password, :password_confirmation, :current_password) }
    end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  before_filter :authenticate_user!, only: [:new,:show]
  before_action :set_post, only: [:new]
  def new

  end

  def show

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:category).permit(:name)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:user_id, :content))
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  def create
    @contact = Contact.new(secure_params)
    if @contact.valid?
      @contact.update_spreadsheet
      UserMailer.contact_email(@contact).deliver
      flash[:notice] = "Message sent from #{@contact.name}."
      redirect_to root_path
    else
      render :new
    end
  end
  private
    def secure_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    #@posts = Post.all
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @category = Category.all.map { |user| [user.name, user.id] }
  end

  # GET /posts/1/edit
  def edit
    @category = Category.all.map { |user| [user.name, user.id] }
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @category = Category.all.map { |user| [user.name, user.id] }
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @category = Category.all.map { |user| [user.name, user.id] }
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id, :category_id, :tag_list)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def tag_cloud(tags, classes)
      max = tags.sort_by(&:count).last
      tags.each do |tag|
        index = tag.count.to_f / max.count * (classes.size - 1)
        yield(tag, classes[index.round])
      end
    end
    def build_categories
      cates = Category.all
      cates.each do |c|
        yield(c,c.name)
      end
    end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/contacts/new.html.erb
<% content_for :title do %>Contact<% end %>
<h3>Contact</h3>
<div class="form">
    <%= simple_form_for @contact do |form| %>
    <%= form.error_notification %>
    <%= form.input :name, autofocus: true %>
    <%= form.input :email %>
    <%= form.input :content, as: :text %>
    <%= form.button :submit, 'Submit', class: 'submit' %>
<% end %>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>
<%=
          link_to 'New Post', new_post_path
          %>
<% end %>
<% @posts.each do |post| %>
<article>
  <h3>
    <a href="#"><%= post.title %></a>
  </h3>
  <h6>
    Written by
    <a href="#"><%= post.user.name %></a> on <%= post.created_at.to_s(:long) %><!-- on August 12, 2012.-->
  </h6>

  <div class="row">
    <div class="large-6 columns">
      <p>
        <%= post.content %>
      </p>
    </div>
    <div class="large-6 columns">
      <img src="http://placehold.it/400x240&text=[img]" />
    </div>
    <p><%= link_to "Comments( #{post.comments.count()} )", post %> </p>
  </div>
</article>
<hr />
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Blog', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul class="right">
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
<li>
    <%=
          link_to current_user.name, edit_user_registration_path
          %></li>
<li>
    <%=
          link_to 'Log Out', destroy_user_session_path, method: :delete
          %></li>

<% else %>

<li>
    <%=
          link_to 'Sign Up', new_user_registration_path, class: "button"
          %></li>
<li>
    <%=
          link_to 'Sign In', new_user_session_path
          %></li>
<% end %>
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Contact', new_contact_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Blog" %>
  ">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" =>
  true %>
  <%# Modernizr is required for Zurb Foundation %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" =>
  true %>
  <%= csrf_meta_tags %></head>
<body>

  <header>
    <%= render 'layouts/navigation' %></header>
  <!-- Main Page Content and Sidebar -->
  <div class="row">
    <!-- Main Blog Content -->
      <%= render 'layouts/messages' %>
      <div class="large-9 columns" role="content">
        <%= yield %>
      </div>
      <!-- End Main Content -->
      <!-- Sidebar -->
      <aside class="large-3 columns">
        <h5>Categories</h5>
        <ul class="side-nav">
        <% build_categories do |c,name| %>
          <li><%= link_to name, "/" %></li>
        <% end %>
        </ul>

        <div class="panel">
          <h5>Featured</h5>
          <p>
            Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow.
          </p>
          <a href="#">Read More &rarr;</a>
        </div>
      </aside>
      <!-- End Sidebar -->

  </div>
  <!-- Footer -->
  <footer class="row">
    <div class="large-12 columns">
      <hr />
      <div class="row">
        <div class="large-6 columns">
          <p>&copy; Copyright no one at all. Go to town.</p>
        </div>
        <div class="large-6 columns">
          <ul class="inline-list right">
            <li>
              <a href="#">Link 1</a>
            </li>
            <li>
              <a href="#">Link 2</a>
            </li>
            <li>
              <a href="#">Link 3</a>
            </li>
            <li>
              <a href="#">Link 4</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About The Blog</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim, mollitia, est voluptatibus molestias possimus expedita pariatur minima rem quae voluptatem animi accusamus ex sint ullam recusandae cupiditate nobis veritatis eligendi.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim, mollitia, est voluptatibus molestias possimus expedita pariatur minima rem quae voluptatem animi accusamus ex sint ullam recusandae cupiditate nobis veritatis eligendi.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim, mollitia, est voluptatibus molestias possimus expedita pariatur minima rem quae voluptatem animi accusamus ex sint ullam recusandae cupiditate nobis veritatis eligendi.</p>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.select :category_id, options_for_select(@category) %>
  </div>
  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>
  <% if user_signed_in? %>
    <%= f.hidden_field :user_id, value: current_user.id %>
  <% end %>
  <div class="actions">
    <%= f.submit nil, class: "button round" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>


<div id="tag_cloud">
  <% tag_cloud Post.tag_counts, %w{s m l} do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th>Category</th>
      <th>Tags</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.user.name %></td>
        <td><%= post.category.name %></td>
        <td><%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @post.category.name %>
</p>

<h2>Comments</h2>
<% @post.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.user.name %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.content %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<% if user_signed_in? %>
  <%= form_for([@post, @post.comments.build]) do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <p>
      <%= f.label :content %><br />
      <%= f.text_area :content, rows: 10 %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>